import ProjectCard from './ProjectCard'
import Reveal from './motion/Reveal'
import { MOTION, staggerDelay } from '../lib/motion'

const projects = [
  {
    number: '01',
    title: 'Vividha Kannada',
    subtitle: 'Multi-Dialect Kannada Intelligence',
    description: [
      'An AI-powered Kannada language framework that identifies regional dialects — Dharwad, Mangaluru, Kundapura, and Standard Kannada — through a hybrid pipeline combining rule-based cues, a trained IndicBERT classifier, and Gemini fallback for hard cases.',
      'It detects Kannada script, Kanglish, and code-mixed text, then normalizes dialectal and romanized input into clean Standard Kannada with an mT5 sequence-to-sequence model, followed by sentiment analysis on the cleaned output.',
      'A FastAPI backend and voice-enabled web interface make it usable both as an everyday app and as a REST API.',
    ],
    category: 'AI / NLP',
    technologies: [
      'Python',
      'NLP',
      'FastAPI',
      'IndicBERT',
      'mT5',
      'Gemini',
    ],
    github:
      'https://github.com/pavanshanthappaiah/vividha-kannada',
  },

  {
    number: '02',
    title: 'Expense Tracker',
    subtitle: 'Personal Finance Platform with AI Assistant',
    description: [
      'A full-stack personal finance application for tracking expenses, managing budgets, and analyzing spending through visual analytics and a calendar view, with recurring expenses scheduled and processed automatically.',
      'Built on a React frontend with a Node.js, Express, and SQL backend, it keeps every expense, budget, and recurrence organized per user behind JWT-based authentication.',
      'An integrated AI chatbot grounds its answers in live app data (RAG) and can add, update, or delete expenses through Model Context Protocol (MCP) tool calling, powered by Gemini or a locally hosted Ollama model.',
    ],
    category: 'Full Stack',
    technologies: [
      'React',
      'Node.js',
      'Express',
      'SQL',
      'REST API',
      'MCP',
      'RAG',
      'Gemini AI',
      'Ollama',
    ],
    github:
      'https://github.com/pavanshanthappaiah/Expense-Tracker',
    live:
      'https://expensetracker00.vercel.app/',
  },

  {
    number: '03',
    title: 'Autonomous Ecom Agent',
    subtitle: 'AI-Powered E-commerce Price Intelligence',
    description: [
      'A full-stack price intelligence platform that tracks products across Amazon, Flipkart, Walmart, eBay, and other e-commerce platforms.',
      'A dedicated Python Flask microservice handles web scraping with BeautifulSoup and Selenium, feeding live prices into a MERN application secured with JWT authentication and backed by on-demand refresh flows and price history.',
      'A Gemini-powered AI assistant completes the experience with context-aware product guidance, real-time streaming responses, and conversation memory.',
    ],
    category: 'AI / E-commerce',
    technologies: [
      'React',
      'Node.js',
      'Express',
      'MongoDB',
      'Python',
      'Flask',
      'BeautifulSoup',
      'Selenium',
      'Gemini AI',
      'JWT',
    ],
    github:
      'https://github.com/pavanshanthappaiah/Autonomous-Ecom-Agent',
  },

  {
    number: '04',
    title: 'Carbon Emission Estimation',
    subtitle: 'Agricultural Carbon Footprint Prediction',
    description: [
      'A machine learning web application that estimates the total carbon footprint of a farm in CO2e, combining emissions from fertilizer use, diesel and electricity consumption, livestock, irrigation, and farming practices using IPCC GWP factors for N2O and CH4.',
      'The FastAPI backend trains and serves Random Forest, XGBoost, and Linear Regression models on an agricultural dataset, with engineered features such as fertilizer-per-acre and livestock totals and a per-source emissions breakdown returned for every prediction.',
      'A React frontend collects crop type, soil type, farming method, and the preferred model, and stores predictions in MongoDB through an async Motor client.',
    ],
    category: 'AI / Agriculture',
    technologies: [
      'Python',
      'FastAPI',
      'React',
      'XGBoost',
      'Scikit-learn',
      'MongoDB',
      'Pandas',
    ],
    github:
      'https://github.com/pavanshanthappaiah/Carbon_emission_Estimation',
  },

  {
    number: '05',
    title: 'MultiMedia Recommender',
    subtitle: 'Books, Movies & Music Recommendations',
    description: [
      'A Streamlit web app that recommends books, movies, or music similar to any title the user enters, returning five curated suggestions with a short description for each.',
      'Recommendations are generated by large language models served through the OpenRouter API, with a switchable model selection (GPT-4o-mini and GPT-4o), category-aware prompting, and a clean single-file Python implementation.',
    ],
    category: 'AI / Recommendation',
    technologies: [
      'Python',
      'Streamlit',
      'OpenRouter API',
      'LLM',
      'REST API',
    ],
    github:
      'https://github.com/pavanshanthappaiah/MultiMedia-Recommender',
  },
]

function Projects() {
  const projectCount = String(projects.length).padStart(2, '0')

  return (
    <section
      id="work"
      className="px-6 py-28 md:px-10 lg:px-16"
    >
      <div className="mx-auto max-w-7xl">

        {/* ==================================================
            SECTION HEADER
        ================================================== */}

        <div className="mb-14">

          <Reveal
            as="p"
            x={-22}
            className="section-eyebrow mb-4 text-sm font-medium uppercase"
          >
            Selected Work
          </Reveal>

          <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end">

            <Reveal delay={MOTION.stagger.base} x={-22}>
              <h2 className="text-4xl font-semibold tracking-[-0.03em] md:text-5xl lg:text-6xl">
                Things I've built.
              </h2>
            </Reveal>

            <Reveal
              as="p"
              delay={MOTION.stagger.loose * 2}
              x={22}
              className="section-intro max-w-md text-sm leading-7 md:text-right"
            >
              A selection of projects where I explore
              artificial intelligence, NLP, machine learning,
              and full-stack development.
            </Reveal>

          </div>

        </div>


        {/* ==================================================
            PROJECT GRID — 3 columns desktop / 2 tablet / 1 mobile
        ================================================== */}

        <div className="grid grid-cols-1 gap-5 md:grid-cols-2 xl:grid-cols-3 xl:gap-6">

          {projects.map((project, index) => (

            <Reveal
              key={project.number}
              delay={staggerDelay(index, MOTION.stagger.base)}
              distance={18}
              className="h-full"
            >
              <ProjectCard project={project} />
            </Reveal>

          ))}

        </div>


        {/* ==================================================
            BOTTOM NOTE
        ================================================== */}

        <Reveal
          delay={MOTION.stagger.loose}
          className="hairline-rule mt-10 flex flex-wrap items-center gap-4 pt-6"
        >

          <p className="text-xs font-medium uppercase tracking-[0.2em]">
            {projectCount} Featured Projects
          </p>

        </Reveal>

      </div>
    </section>
  )
}

export default Projects
